### ISSUE TITLE
Minor things, major thanks

### ISSUE THREAD

**Issue by rubydesign** [acecilia/OpenWRTInvasion#127]
Hi,
so i just flashed 20 xiaomi 4a giga devices. Great devices, but completely unusable for my vlan without you guys. So thanks, and if you have a coffee account i'm happy to send one.

The minor things were
- the default address. I always typed 192.168.31.1 (as i had a wired connection). Maybe this is different when you work over wifi.
- I had difficulties downloading the firmware, once i ssh'd . Any secure downloads worked unreliably, some yes, sometimes 4 times no. And i did not know why. I had hosted on github, then my own, but reliably only once i had a http (no s) location.
So i was wondering if it is possible to push them or use the local machine/software to host them.

Anyway, minor things, major thanks!!

**Comment by acecilia** [comment]
Thanks! I do not have a coffee account, glad the script was useful. Since I rely on the work of others, I am happy to provide this for free 😄 

> the default address
I think this depends on your network setup

> So i was wondering if it is possible to push them or use the local machine/software to host them
It is probably possible. I do not think there is anything to be done in our side. After exploit, you can use any of the tools in the router to fetch anything you need from local machine. But I have never done it, so if you find a way lemme know and I will add it to the readme
